### ISSUE TITLE
Facial informtion class labels

### ISSUE THREAD

**Issue by Drunkar** [ivclab/CPG#5]
Can I ask about the label name for each class in facial informatics tasks?
Seems to be:

## gender: Are these correct?:
- 0: Male
- 1: Female
- 2: Unknown

## Emotion: Are these correct?:
- 0: Neutral
- 1: Happy
- 2: Sad
- 3: Surprise
- 4: Fear
- 5: Disgust
- 6: Angry

## Age
- What are the age ranges for each of 8 classes?

Thanks

**Comment by Jia-HongHenryLee** [comment]
Hi @Drunkar,

Thank you for the fact that you are interested in our paper.

Gender => Correct
Emotion => Correct
Age => 0-2, 4-6, 8-13,  15-20, 25-32, 38-43, 48-53, 60-

**Comment by Drunkar** [comment]
@Jia-HongHenryLee Thank you!
